# Generated by Django 5.2.7 on 2025-11-02 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garagem1',
            fields=[
                ('garagem_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carro1',
            fields=[
                ('carro_id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Gasoleo', 'Gasoleo'), ('Hibrido', 'Hibrido'), ('Eletrico', 'Eletrico'), ('Outro', 'Outro')], max_length=20, verbose_name='Combustivel')),
                ('tdi', models.FloatField(blank=True, null=True, verbose_name='TDI')),
                ('cavalos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cavalos')),
                ('transmissao', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Semi-automatic', 'Semi-automatic'), ('CVT', 'CVT'), ('Other', 'Other')], max_length=20, verbose_name='Transmissao')),
                ('kilometragem', models.PositiveIntegerField(verbose_name='Kilometragem')),
                ('ano_produzido', models.PositiveIntegerField(verbose_name='Ano Produzido')),
                ('tipo_corpo', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Van', 'Van'), ('Pickup', 'Pickup'), ('Other', 'Other')], max_length=20, null=True, verbose_name='Tipo Corpo')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('matricula', models.CharField(max_length=8, null=True, verbose_name='Matricula')),
                ('garagem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garagem1')),
            ],
        ),
    ]
