# Generated by Django 5.2.7 on 2025-11-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carro1',
            new_name='Carro',
        ),
        migrations.RenameModel(
            old_name='Garagem1',
            new_name='Garagem',
        ),
    ]
