# Generated by Django 5.2.7 on 2025-11-02 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_carro1_carro_rename_garagem1_garagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('criado_a', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='garagem',
            name='nome',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garagem',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.utilizador'),
            preserve_default=False,
        ),
    ]
