# Generated by Django 5.2.7 on 2025-10-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carinfo_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinfo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='transmission',
        ),
    ]
