# Generated by Django 5.2.7 on 2025-10-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_carinfo_color_remove_carinfo_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='specs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
