# Generated by Django 5.2.7 on 2025-11-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_utilizador_garagem_nome_alter_garagem_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='matricula',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='tipo_corpo',
            field=models.CharField(blank=True, choices=[('Seda', 'Sedã'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Cope', 'Cupê'), ('Conversivel', 'Conversível'), ('Carrinha', 'Carrinha'), ('Van', 'Van'), ('Pickup', 'Pickup'), ('Outro', 'Outro')], max_length=20, null=True, verbose_name='Tipo Corpo'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='transmissao',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatico', 'Automatico'), ('Semi-automatico', 'Semi-automatico'), ('CVT', 'CVT'), ('Outro', 'Outro')], max_length=20, verbose_name='Transmissao'),
        ),
    ]
