# Generated by Django 5.2.7 on 2025-11-02 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_carro_matricula_alter_carro_tipo_corpo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='tdi',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Manutenção',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Dia da Manutenção')),
                ('kilometragem', models.PositiveIntegerField(verbose_name='Kilometragem')),
                ('carro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carro')),
            ],
        ),
    ]
