# Generated by Django 5.2.7 on 2025-10-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_carinfo_specs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='specs',
            new_name='cronic',
        ),
    ]
