# Generated by Django 5.2.7 on 2025-11-02 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_carro_tdi_manutenção'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutenção',
            old_name='cost',
            new_name='custo',
        ),
        migrations.RenameField(
            model_name='manutenção',
            old_name='date',
            new_name='data',
        ),
        migrations.CreateModel(
            name='Cronico',
            fields=[
                ('problema_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('kilometragem', models.PositiveIntegerField(verbose_name='Kilometragem')),
                ('severidade', models.CharField(blank=True, choices=[('nenhuma', 'Nenhuma'), ('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=7, null=True, verbose_name='Severidade')),
                ('resolvido', models.BooleanField(default=False)),
                ('carro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carro')),
            ],
        ),
    ]
