# Generated by Django 5.2.7 on 2025-11-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_cost_manutenção_custo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='garagem_id',
            new_name='garagem',
        ),
    ]
