# Generated by Django 5.2.7 on 2025-11-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_garagem_id_carro_garagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronico',
            old_name='carro_id',
            new_name='carro',
        ),
        migrations.RenameField(
            model_name='garagem',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='manutenção',
            old_name='carro_id',
            new_name='carro',
        ),
    ]
