# Generated by Django 5.2.7 on 2025-11-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_carro_id_cronico_carro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='tdi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
