# Generated by Django 5.2.7 on 2025-11-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_carro_tdi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manutenção',
            new_name='Manutencao',
        ),
    ]
