# Generated by Django 5.2.7 on 2025-11-13 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_manutenção_manutencao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='kilometragem',
        ),
        migrations.RemoveField(
            model_name='cronico',
            name='kilometragem',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='kilometragem',
        ),
        migrations.AddField(
            model_name='carro',
            name='quilometragem',
            field=models.PositiveIntegerField(default=1, verbose_name='Quilometragem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cronico',
            name='quilometragem',
            field=models.PositiveIntegerField(default=1, verbose_name='Quilometragem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manutencao',
            name='quilometragem',
            field=models.PositiveIntegerField(default=1, verbose_name='Quilometragem'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Defenicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilizador')),
            ],
        ),
    ]
